<?xml version="1.0"?>
<package format="3">
  <name>fyt_pos</name>
  <version>0.1.0</version>
  <description>比赛场地定位、区域判定与 RViz 可视化。</description>
  <maintainer email="upre@todo.todo">upre</maintainer>
  <license>Apache-2.0</license>

  <depend>ament_index_python</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>