<?xml version="1.0"?>
<package format="3">
  <name>yolo_3d_detect_pkg</name>
  <version>0.1.0</version>
  <description>比赛灵石与大地块 RGB-D 视觉检测。</description>
  <maintainer email="upre@todo.todo">upre</maintainer>
  <license>Apache-2.0</license>

  <depend>ament_index_python</depend>
  <depend>cv_bridge</depend>
  <depend>geometry_msgs</depend>
  <depend>message_filters</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>

  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>